### ISSUE TITLE
bug: unable to recover eth address from signature

### ISSUE THREAD

**Issue by Dev9133** [immutable/imx-core-sdk-golang#81]
### Steps to reproduce

```
git clone https://github.com/immutable/imx-core-sdk-golang.git
cd imx-core-sdk-golang/imx/examples/minting
cp .env.example .env
// .env STARK_PRIVATE_KEY=""
// .env ETH_NETWORK="sandbox"
// .env rest of .env values
go build && ./minting
```
### Additional info
I was able to successfully create a project, collection and set collection metadata using go sdk. Only mint gave me the error.

### Error
2022/10/14 16:23:02 
POST /v2/mints HTTP/1.1
Host: api.sandbox.x.immutable.com
User-Agent: OpenAPI-Generator/0.2.1/go
Content-Length: 500
Accept: application/json
Content-Type: application/json
X-Sdk-Version: imx-core-sdk-golang-0.2.1
Accept-Encoding: gzip

[{"auth_signature":"0xa9a8a2918fa9df1cbf44853a1ed6c7142b97b90bad0606683f367dcaa963bf8644ee695169ffe3d6c88e4ee4325b0fa16ef79b88501b15b902727354acbfeb9400","contract_address":"0xAca938C9B07E681Fa01cD7174D6CB272Cb5b4214","royalties":[{"percentage":1,"recipient":"0x49343FB21B2ff7cdf0E723a88be9d2e0890bF96a"}],"users":[{"tokens":[{"blueprint":"123","id":"0","royalties":[{"percentage":1,"recipient":"0x49343FB21B2ff7cdf0E723a88be9d2e0890bF96a"}]}],"user":"0x49343FB21B2ff7cdf0E723a88be9d2e0890bF96a"}]}]

2022/10/14 16:23:03 
HTTP/2.0 400 Bad Request
Content-Length: 223
Content-Type: application/json
Date: Fri, 14 Oct 2022 19:23:03 GMT
Mint_limit: 50000
Mint_limit_reset: 1668191200
Mint_remaining: 49977
Vary: Origin
Vary: Origin
Via: 1.1 d3e98d8cca4d16199794e4f4191b942c.cloudfront.net (CloudFront)
X-Amz-Apigw-Id: aAmLoHh_CYcFf9A=
X-Amz-Cf-Id: Pq-AdUdwNN6hefFc4JTuPrY7AfBksnHDNxvuHGaznEbcd2p5IF2tsw==
X-Amz-Cf-Pop: HEL51-P1
X-Amzn-Remapped-Content-Length: 223
X-Amzn-Remapped-Date: Fri, 14 Oct 2022 19:23:03 GMT
X-Amzn-Remapped-Server: istio-envoy
X-Amzn-Requestid: 91257b9d-a433-4a82-8e61-505522aabd8f
X-Cache: Error from cloudfront
X-Envoy-Upstream-Service-Time: 411

`{"code":"mint_validation_failed","message":"unable to recover eth address from signature 0xa9a8a2918fa9df1cbf44853a1ed6c7142b97b90bad0606683f367dcaa963bf8644ee695169ffe3d6c88e4ee4325b0fa16ef79b88501b15b902727354acbfeb9400"}
2022/10/14 16:23:03 error in minting.MintTokensWorkflow: Request URL: https://api.sandbox.x.immutable.com/v2/mints Status: 400, Message: unable to recover eth address from signature 0xa9a8a2918fa9df1cbf44853a1ed6c7142b97b90bad0606683f367dcaa963bf8644ee695169ffe3d6c88e4ee4325b0fa16ef79b88501b15b902727354acbfeb9400
panic: error in minting.MintTokensWorkflow: Request URL: https://api.sandbox.x.immutable.com/v2/mints Status: 400, Message: unable to recover eth address from signature 0xa9a8a2918fa9df1cbf44853a1ed6c7142b97b90bad0606683f367dcaa963bf8644ee695169ffe3d6c88e4ee4325b0fa16ef79b88501b15b902727354acbfeb9400

goroutine 1 [running]:
log.Panicf({0x957914?, 0xa12088?}, {0xc00059fec0?, 0xa11c60?, 0xc000363c80?})
	/usr/local/go/src/log/log.go:392 +0x67
main.main()
	/imx-core-sdk-golang/imx/examples/minting/main.go:51 +0x3fe`

**Comment by suluvai** [comment]
@Dev9133 Thank you for reporting this issue. There was a bug in the collections example, we have resolved the issue in this PR, please see https://github.com/immutable/imx-core-sdk-golang/pull/82

You may need to re-create a new collection and use that for minting.
