### ISSUE TITLE
api.NewClient() missing metadataRefreshApi initialization

### ISSUE THREAD

**Issue by alyssathi** [immutable/imx-core-sdk-golang#87]
interface.go
just missing at line:97:
`c.metadataRefreshesAPI = apiClient.MetadataRefreshesApi`

**Comment by suluvai** [comment]
Thank you @alyssathi for reporting this issue. Will fix this shortly.

**Comment by suluvai** [comment]
Fixed by https://github.com/immutable/imx-core-sdk-golang/pull/91
