### ISSUE TITLE
Difficult to set server url configs to mainnet

### ISSUE THREAD

**Issue by alyssathi** [immutable/imx-core-sdk-golang#88]
`func NewConfiguration() *Configuration {
	cfg := &Configuration{
		DefaultHeader:    make(map[string]string),
		UserAgent:        "OpenAPI-Generator/0.2.1/go",
		Debug:            false,
		Servers:          ServerConfigurations{
			{
				URL: "https://api.sandbox.x.immutable.com",
				Description: "No description provided",
			},
		},
		OperationServers: map[string]ServerConfigurations{
		},
	}
	return cfg
}`

hard coded  "https://api.sandbox.x.immutable.com" server configs without variable makes it hard to use NewConfiguration() dynamically

**Comment by suluvai** [comment]
Hey @alyssathi, here is how you can select the environment https://github.com/immutable/imx-core-sdk-golang/blob/main/imx/examples/common/common.go#L36
Here are the list of pre-configured environments you can use https://github.com/immutable/imx-core-sdk-golang/blob/main/imx/interface.go#L13

**Comment by alyssathi** [comment]
hey thanks for the response, I see that however I'm using the NewConfiguration() function to get back apiConfiguration and within the configuration it has the hardcoded URL of "https://api.sandbox.x.immutable.com" which isnt dependent on network
 
```
func NewConfiguration() *Configuration {
	cfg := &Configuration{
		DefaultHeader:    make(map[string]string),
		UserAgent:        "OpenAPI-Generator/0.2.1/go",
		Debug:            false,
		Servers:          ServerConfigurations{
			{
				URL: "https://api.sandbox.x.immutable.com", **here
				Description: "No description provided",
			},
		},
		OperationServers: map[string]ServerConfigurations{
		},
	}
	return cfg
}
```

**Comment by alyssathi** [comment]
Could possibly change the function to take an environment?

```
func NewConfiguration(environment *Environment) *Configuration {
	cfg := &Configuration{
		DefaultHeader:    make(map[string]string),
		UserAgent:        "OpenAPI-Generator/0.2.1/go",
		Debug:            false,
		Servers:          ServerConfigurations{
			{
				URL: environment.BaseAPIPath,                **here
				Description: "No description provided",
			},
		},
		OperationServers: map[string]ServerConfigurations{
		},
	}
	return cfg
}
```

**Comment by suluvai** [comment]
@alyssathi  `NewConfiguration` is auto generated code and as per the Open API 3.0 spec it supports having multiple servers in the configuration list. The solution provided in examples will add the new server url and uses that for performing requests.
