### ISSUE TITLE
DemoTransferWorkFlow is failing due to "invalid_stark_signature"

### ISSUE THREAD

**Issue by sumitbhowmick** [immutable/imx-core-sdk-golang#94]
@suluvai I'm trying to transfer an amount as per following example.
https://github.com/immutable/imx-core-sdk-golang/blob/main/imx/examples/transfer/main.go

**Additional Info**
I kept STARK_PRIVATE_KEY_IN_HEX blank to have it auto-generated using the SDK. Tried with pre-generated Stark-key and found same result.

**Steps to reproduce:**
````
func main() {
	//CommonInitialise(".env")
	ctx, envs, cl, l1signer, l2signer := CommonInitialise(".env")
	// Transfer workflow demo
	DemoTransferWorkflow(ctx, cl, l1signer, l2signer, envs)
}
````
It is failing due to following error

2022/11/14 16:57:10 
HTTP/2.0 401 Unauthorized
Content-Length: 210
Content-Type: application/json
Date: Mon, 14 Nov 2022 11:27:10 GMT
Vary: Origin
Vary: Origin
Via: 1.1 2ec72a3e72a08b5f1d2e07fe02b4fea0.cloudfront.net (CloudFront)
X-Amz-Apigw-Id: blriMHxQCYcF4tg=
X-Amz-Cf-Id: x5ygzbMj7ICBLC7FXPjkhF_BmLn6GhN78Ra9JQ_9YoBfJ6YR1ZmyTA==
X-Amz-Cf-Pop: CCU50-P2
X-Amzn-Remapped-Content-Length: 210
X-Amzn-Remapped-Date: Mon, 14 Nov 2022 11:27:10 GMT
X-Amzn-Remapped-Server: istio-envoy
X-Amzn-Requestid: 39eb2d32-0990-45c9-a474-7a3489601205
X-Cache: Error from cloudfront
X-Envoy-Upstream-Service-Time: 918

{"code":"invalid_stark_signature","message":"unable to verify stark signature 0x01ac0b0b4ed81dd46de6fdb785d6b2f9ebcf4021b0f557bbcc6e6264a58d55e7045cf4a1f1ebeca1eb3f11e6f7c2e733344a146ad9ad577dfe247affa629b01f"}
2022/11/14 16:57:10 error calling transfer workflow: Request URL: https://api.sandbox.x.immutable.com/v1/transfers Status: 
401, Message: unable to verify stark signature 0x01ac0b0b4ed81dd46de6fdb785d6b2f9ebcf4021b0f557bbcc6e6264a58d55e7045cf4a1f1ebeca1eb3f11e6f7c2e733344a146ad9ad577dfe247affa629b01f
panic: error calling transfer workflow: Request URL: https://api.sandbox.x.immutable.com/v1/transfers Status: 401, Message: unable to verify stark signature 0x01ac0b0b4ed81dd46de6fdb785d6b2f9ebcf4021b0f557bbcc6e6264a58d55e7045cf4a1f1ebeca1eb3f11e6f7c2e733344a146ad9ad577dfe247affa629b01f

goroutine 1 [running]:
log.Panicf({0x7ff6e5a3cf53?, 0xa?}, {0xc00079fed0?, 0x2a?, 0xc00032bb30?})
        C:/Program Files/Go/src/log/log.go:392 +0x67
main.DemoTransferWorkflow({0x7ff6e5b030e8, 0xc000020048}, 0x7ff6e54a4ba7?, {0x7ff6e5b02da8?, 0xc0001fc3c0?}, {0x7ff6e5b02268, 0xc000086020}, 0xc000050000?)
        C:/ilv-repo/k6/signer/imxinit.go:108 +0x2f2
main.main()
        C:/ilv-repo/k6/signer/imxinit.go:25 +0x3f
exit status 2

**Comment by suluvai** [comment]
@sumitbhowmick I just re-tested this and it works fine, although I only tested with my pre-generated stark key value.

**Comment by suluvai** [comment]
@sumitbhowmick can you please check your user details using this endpoint https://docs.x.immutable.com/reference/#/operations/getUsers and send us the response please?

**Comment by suluvai** [comment]
So it works when you use pre-generated stark key? There can only be one stark key associated with each ethereum wallet.

**Comment by sumitbhowmick** [comment]
It does not work, if the pre-generated stark key is generated using stark.GenerateKey() function provided in the core-sdk.
It works if the pre-generated stark key is generated using https://github.com/immutable/generate-stark-key

What I understand now, 
1. the wallet need to be registered with IMX before attempting a transfer. 
2. To register a wallet, in the first place we need to provide both L1 & stark key. 
3. A wallet can have only one stark key associated, which is registered with IMX. The same key must be provided while transferring.
So, essentially the flow involving stark.GenerateKey() during transfer should never occur.
Is my understanding correct?

**Comment by suluvai** [comment]
I see the problem,

1. Correct the user needs to be registered already to perform transfer. If the user is not registered, you will receive the response as
`{"code":"bad_request","message":"sender '0x9D8F5Cd78F084cf3f1906047a88c8Df9f01304C9' does not exist"}`

2. To Register a wallet you only need to provide L1 and Stark Key can be randomly generated or can use the pre-generated stark key. Note if you use randomly generated stark key you need to store that value and use that for subsequent operations needing a stark signer for that account. As you can only have one account associated with each L1 wallet.

3. Yes you will need to use the same stark key for all subsequent operations associated with that account.

**Comment by suluvai** [comment]
Will update examples to accept the passed in stark key only for Transfer example.

**Comment by sumitbhowmick** [comment]
That would be helpful.
Will like to see this library eventually mature like its javascript counterpart. Generation of stark key and wallet registration should ideally be taken care of. Till that maturity arrives, it may be helpful to list out the prerequisites to execute each function (like transfer or deposit).
